name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        env:
          GOOS: windows
        run: go build -o wsl2-ssh-bridge.exe -ldflags -H=windowsgui main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact Name
          name: wsl2-ssh-bridge.exe
          # The directory containing files to upload.
          path: wsl2-ssh-bridge.exe
